### PR TITLE
Feature/angular material gui experiment

### PR DESCRIPTION
**Pull request by pavoni**
Switched to use Angular Material on @InsidersByte's suggestion.

Much better - so let's go with it!

### CODE REVIEW

**Comment by pavoni** [comment]
Awesome slider now gone.

On moving the Angular Material .config - happy to move - where would you put it / how would you move it? (I just copied the demo examples - probably not the greatest idea!).

**Comment by InsidersByte** [comment]
Awesome :+1: 

It should only take a minute I can do it.

**Comment by InsidersByte** [comment]
I have updated the Mortgage Calculator Service and tidied it up a little. I will stick some comments in the commit to explain why I did some of the things I did.

**Comment by InsidersByte** [comment]
I have refactored the configuration to it's own module

**Comment by pavoni** [comment]
Thanks for going through this, really helpful! 

As you know I’m a Javascript beginner - so just wanted to make sure I’ve understood for next time :-)

1.) ‘let' vs ‘var' - cool thanks - didn’t know about this. ‘let' is scoped more like a proper programming language :-)

2.) scope of instance variables. I wasn’t sure of the rules so was being over cautious. Looking at what you’ve done:-
 	'my_instance = your_instance’ will default to 'this.my_instance = this.your_instance’ (assuming the instance variables exist).
	To do this in Ruby you need to write ’this.my_instance = your_instance’ (Ruby is wrong here, and C++ (and probably Javascript) are right!!) 

3.) Factory vs Service. So in a Factory each method is creating a new method, to try and do the same as a Ruby MyClass.ne. I was aware I was probably only creating a single instance of my module - so my ‘instance’ variables were actually class variables = dangerous! My remaining question is when does the factory create a new instance? I assume when you load a module that refers to it as a dependency? So the ‘rule’ should be that if you have any ‘instance’ variables you should always create a factory. Services should be methods with no instance data? (Will have to adjust to the fact that Javascript isn’t a proper OO Language!)

4.) Angular config can be in any of the code that gets initially loaded.

5.) Anything else I missed?

Will merge - but I think the comments stay!

**Comment by InsidersByte** [comment]
No worries, I only went through a couple of things, will do more in a just over a couple of weeks!

That is great, it also means I have to look things up just to double check my understanding, which is good for me.

1. Yes let and const are both block scoped variables instead of var which is function scoped. They are both part of the ECMAScript 6 standard. See (http://es6-features.org/).

2. Yes that is the case. I don't really like to use `this` that much. I tend to assign `this` to a variable  like `self`. This is because `this` can have some unintended behaviours because of scoping.

3. Factories in Angular are Singletons so only one instance of them exists. Here is a stackoverflow link that might help explain the difference more (http://stackoverflow.com/questions/14324451/angular-service-vs-angular-factory).

4. Yep that is true.

5. Did you look at how I created the module for the configuration and how that could apply to the mortgage calculator?

**Comment by pavoni** [comment]
On 5 - no missed that - will take a look next week...

**Pull request merged**
