### PR TITLE
Add gulp

### PR DESCRIPTION
**Pull request by pavoni**
Harder to get the paths right than I was expecting!

Comments welcome!

### CODE REVIEW

**Comment by InsidersByte** [comment]
I have modified the gulp tasks around a bit and used wiredep (https://github.com/taptapship/wiredep) instead of main bower files. I also restructured the files into a public folder (more for when we start on the server, but also because my personal gulp things I copied in work from that folder :+1:)

**Comment by InsidersByte** [comment]
It will be easier to get the paths right when it is all handled by node! Because a root / won't mean the root of your drive.

**Comment by InsidersByte** [comment]
There is loads more we will do with gulp. But I can do that when I start.

**Comment by pavoni** [comment]
Cool - thanks for your help.

I fixed a small typo direct in develop

**Comment by InsidersByte** [comment]
The things we probably want to do are:

* Run jshint and jscs
* Run tests
* Run development environment
* Build production code
* Run production environment
* compile our css (if we use a css preprocessor)
* copy fonts and images to build folder
* concat and uglify our javascript
* concat and minify our css
* bump our version numbers
* build our angular template cache

**Comment by InsidersByte** [comment]
Woops on the typo front. Have you committed it as I cannot see it?

**Comment by pavoni** [comment]
Forgot to push - now done.

Not a big deal - it was easy to spot.

On 1 Sep 2015, at 10:33, Jonathon Kelly <notifications@github.com<mailto:notifications@github.com>> wrote:


Woops on the typo front. Have you committed it as I cannot see it?

**Pull request merged**
